package ni.gob.inss.sisinv.model.entity.catalogo;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import ni.gob.inss.barista.model.entity.EntityBase;

/**
 * CaracteristicasHardware generated by hbm2java
 */
@Entity
@Table(name = "caracteristicas_hardware", schema = "catalogo")
public class CaracteristicasHardware extends EntityBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer tipoCaracteristicaId;
	private Integer caracteristicaId;
	private String descripcion;
	private boolean pasivo;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tipo_medida_id", nullable = false)
	public Integer getTipoCaracteristicaId() {
		return tipoCaracteristicaId;
	}

	public void setTipoCaracteristicaId(Integer tipoCaracteristicaId) {
		this.tipoCaracteristicaId = tipoCaracteristicaId;
	}

	@Column(name = "medida_id", nullable = false)
	public Integer getCaracteristicaId() {
		return caracteristicaId;
	}

	public void setCaracteristicaId(Integer caracteristicaId) {
		this.caracteristicaId = caracteristicaId;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "pasivo", nullable = false)
	public boolean isPasivo() {
		return this.pasivo;
	}

	public void setPasivo(boolean pasivo) {
		this.pasivo = pasivo;
	}

}
