package ni.gob.inss.sisinv.model.entity.catalogo;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import ni.gob.inss.barista.model.entity.EntityBase;
import ni.gob.inss.barista.model.entity.catalogo.Catalogo;

/**
 * CaracteristicasHardware generated by hbm2java
 */
@Entity
@Table(name = "caracteristicas_hardware", schema = "catalogo")
@SequenceGenerator(name="CaracateristicasHardwareSerial",  allocationSize=1, sequenceName=" catalogo.caracteristicas_hardware_id_seq")
public class CaracteristicasHardware extends EntityBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String descripcion;
	private boolean pasivo;
	private Integer caracteristicaPadreId;
	private Integer tipoActivoId;
	private Catalogo oTipoActivo;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(generator="CaracateristicasHardwareSerial", strategy=GenerationType.SEQUENCE)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "pasivo", nullable = false)
	public boolean isPasivo() {
		return this.pasivo;
	}

	public void setPasivo(boolean pasivo) {
		this.pasivo = pasivo;
	}

	@Column(name="caracteristica_padre_id")
	public Integer getCaracteristicaPadreId() {
		return caracteristicaPadreId;
	}

	public void setCaracteristicaPadreId(Integer caracteristicaPadreId) {
		this.caracteristicaPadreId = caracteristicaPadreId;
	}

	@Column(name="tipo_activo_id", insertable=true, updatable=true)
	public Integer getTipoActivoId() {
		return tipoActivoId;
	}

	public void setTipoActivoId(Integer tipoActivoId) {
		this.tipoActivoId = tipoActivoId;
	}

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="tipo_activo_id", insertable=false, updatable=false)
	public Catalogo getoTipoActivo() {
		return oTipoActivo;
	}

	public void setoTipoActivo(Catalogo oTipoActivo) {
		this.oTipoActivo = oTipoActivo;
	}

}
