package ni.gob.inss.sisinv.model.entity.catalogo;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import ni.gob.inss.barista.model.entity.EntityBase;

/**
 * Delegacion generated by hbm2java
 */
@Entity
@Table(name = "delegacion", schema = "catalogo")
@SequenceGenerator(name="Delegacion_SEQ", sequenceName="catalogo.delegacion_id_seq", allocationSize=1)
public class Delegacion extends EntityBase{

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nombre;
	private Integer departamentoId;
	private Boolean pasivo;
	private List<Empleado> empleados = new ArrayList<Empleado>();


	@Id
	@Column(name = "id", unique = true, nullable = false, insertable=true,columnDefinition="serial")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="Delegacion_SEQ")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "departamento_id", nullable = false)
	public Integer getDepartamentoId() {
		return this.departamentoId;
	}

	public void setDepartamentoId(Integer departamentoId) {
		this.departamentoId = departamentoId;
	}

	@Column(name = "pasivo", nullable = false)
	public Boolean getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(Boolean pasivo) {
		this.pasivo = pasivo;
	}

	@OneToMany(mappedBy = "delegacion")
	public List<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(List<Empleado> empleados) {
		this.empleados = empleados;
	}

}
