package ni.gob.inss.sisinv.model.entity.catalogo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Delegacion generated by hbm2java
 */
@Entity
@Table(name = "delegacion", schema = "catalogo")
public class Delegacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2572916685516311996L;
	private Integer id;
	private String nombre;
	private Integer departamentoId;
	private Date creadoEl;
	private Date modificadoEl;
	private Integer creadoPor;
	private Integer modificadoPor;
	private Boolean pasivo;
	private List<Empleado> empleados = new ArrayList<Empleado>();

	public Delegacion() {
	}

	public Delegacion(Integer id, String nombre, Integer departamentoId, Date creadoEl, Integer creadoPor,
			Boolean pasivo) {
		this.id = id;
		this.nombre = nombre;
		this.departamentoId = departamentoId;
		this.creadoEl = creadoEl;
		this.creadoPor = creadoPor;
		this.pasivo = pasivo;
	}

	public Delegacion(Integer id, String nombre, Integer departamentoId, Date creadoEl, Date modificadoEl,
			Integer creadoPor, Integer modificadoPor, Boolean pasivo, List<Empleado> empleados) {
		this.id = id;
		this.nombre = nombre;
		this.departamentoId = departamentoId;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.creadoPor = creadoPor;
		this.modificadoPor = modificadoPor;
		this.pasivo = pasivo;
		this.empleados = empleados;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, columnDefinition="serial")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "departamento_id", nullable = false)
	public Integer getDepartamentoId() {
		return this.departamentoId;
	}

	public void setDepartamentoId(Integer departamentoId) {
		this.departamentoId = departamentoId;
	}

	@Column(name = "creado_el", nullable = false, length = 29)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Column(name = "modificado_el", length = 29)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "creado_por", nullable = false)
	public Integer getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(Integer creadoPor) {
		this.creadoPor = creadoPor;
	}

	@Column(name = "modificado_por")
	public Integer getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(Integer modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

	@Column(name = "pasivo", nullable = false)
	public Boolean getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(Boolean pasivo) {
		this.pasivo = pasivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "delegacion")
	public List<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(List<Empleado> empleados) {
		this.empleados = empleados;
	}

}
