package ni.gob.inss.sisinv.model.entity.catalogo;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import ni.gob.inss.barista.model.entity.EntityBase;
import ni.gob.inss.sisinv.model.entity.inventario.Activos;

/**
 * Delegacion generated by hbm2java
 */
@Entity
@Table(name = "delegacion", schema = "catalogo")
@SequenceGenerator(name="Delegacion_SEQ", sequenceName="catalogo.delegacion_id_seq", allocationSize=1)
public class Delegacion extends EntityBase{

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String descripcion;
	private Integer departamentoId;
	private Boolean pasivo;
	private Boolean esUbicacion;
	private List<Empleado> empleados = new ArrayList<Empleado>();
	private List<Activos> listaActivos = new ArrayList<Activos>();

	@Id
	@Column(name = "id", unique = true, nullable = false, insertable=true,columnDefinition="serial")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="Delegacion_SEQ")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 25)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String nombre) {
		this.descripcion = nombre;
	}

	@Column(name = "departamento_id", nullable = false)
	public Integer getDepartamentoId() {
		return this.departamentoId;
	}

	public void setDepartamentoId(Integer departamentoId) {
		this.departamentoId = departamentoId;
	}

	@Column(name = "pasivo", nullable = false)
	public Boolean getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(Boolean pasivo) {
		this.pasivo = pasivo;
	}

	@OneToMany(mappedBy = "delegacion")
	public List<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(List<Empleado> empleados) {
		this.empleados = empleados;
	}

	@OneToMany(mappedBy = "ubicacion")	
	public List<Activos> getListaActivos() {
		return listaActivos;
	}

	public void setListaActivos(List<Activos> listaActivos) {
		this.listaActivos = listaActivos;
	}

	@Column(name="ubicacion")
	public Boolean getEsUbicacion() {
		return esUbicacion;
	}

	public void setEsUbicacion(Boolean esUbicacion) {
		this.esUbicacion = esUbicacion;
	}
	
	
}
