package ni.gob.inss.sisinv.model.entity.catalogo;

import java.util.Date;

// default package
// Generated 07-12-2016 04:38:35 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado", schema = "catalogo")
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2225725153178619039L;
	private Integer id;
	private Delegacion delegacion;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private Integer tipoIdentificacion;
	private String nroIdentificacion;
	private Boolean pasivo;
	private Date creadoEl;
	private Date modificadoEl;
	private Integer creadoPor;
	private Integer modificadoPor;

	public Empleado() {
	}

	public Empleado(Integer id, String primerNombre, String primerApellido, Integer tipoIdentificacion,
			String nroIdentificacion, Boolean pasivo, Date creadoEl, Integer creadoPor) {
		this.id = id;
		this.primerNombre = primerNombre;
		this.primerApellido = primerApellido;
		this.tipoIdentificacion = tipoIdentificacion;
		this.nroIdentificacion = nroIdentificacion;
		this.pasivo = pasivo;
		this.creadoEl = creadoEl;
		this.creadoPor = creadoPor;
	}

	public Empleado(Integer id, Delegacion delegacion, String primerNombre, String segundoNombre, String primerApellido,
			String segundoApellido, Integer tipoIdentificacion, String nroIdentificacion, Boolean pasivo, Date creadoEl,
			Date modificadoEl, Integer creadoPor, Integer modificadoPor) {
		this.id = id;
		this.delegacion = delegacion;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.tipoIdentificacion = tipoIdentificacion;
		this.nroIdentificacion = nroIdentificacion;
		this.pasivo = pasivo;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.creadoPor = creadoPor;
		this.modificadoPor = modificadoPor;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, columnDefinition="serial")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "delegacion_id")
	public Delegacion getDelegacion() {
		return this.delegacion;
	}

	public void setDelegacion(Delegacion delegacion) {
		this.delegacion = delegacion;
	}

	@Column(name = "primer_nombre", nullable = false, length = 25)
	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	@Column(name = "segundo_nombre", length = 25)
	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	@Column(name = "primer_apellido", nullable = false, length = 25)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido", length = 25)
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "tipo_identificacion", nullable = false)
	public Integer getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(Integer tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	@Column(name = "nro_identificacion", nullable = false, length = 20)
	public String getNroIdentificacion() {
		return this.nroIdentificacion;
	}

	public void setNroIdentificacion(String nroIdentificacion) {
		this.nroIdentificacion = nroIdentificacion;
	}

	@Column(name = "pasivo", nullable = false)
	public Boolean getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(Boolean pasivo) {
		this.pasivo = pasivo;
	}

	@Column(name = "creado_el", nullable = false, length = 29)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Column(name = "modificado_el", length = 29)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "creado_por", nullable = false)
	public Integer getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(Integer creadoPor) {
		this.creadoPor = creadoPor;
	}

	@Column(name = "modificado_por")
	public Integer getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(Integer modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

}
