package ni.gob.inss.sisinv.model.entity.catalogo;
// default package
// Generated 09-22-2016 09:39:20 AM by Hibernate Tools 4.3.4.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import ni.gob.inss.barista.model.entity.EntityBase;
import ni.gob.inss.sisinv.model.entity.inventario.Activos;

/**
 * MarcasModelos generated by hbm2java
 */
@Entity
@Table(name = "marcas_modelos", schema = "catalogo")
@SequenceGenerator(name="MarcasModelos_SEQ", sequenceName="catalogo.marcas_modelos_id_seq", allocationSize=1)
public class MarcasModelos extends EntityBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	public String descripcion;
	private Integer padreId;
	private boolean pasivo;
	private List<Activos> listaMarcaActivo = new ArrayList<Activos>();
	private List<Activos> listaModeloActivo = new ArrayList<Activos>();
	
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MarcasModelos_SEQ")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "padre_id", nullable = false)
	public Integer getPadreId() {
		return this.padreId;
	}

	public void setPadreId(Integer padreId) {
		this.padreId = padreId;
	}
	
	@OneToMany(mappedBy="marca", fetch=FetchType.LAZY)
	public List<Activos> getListaMarcaActivo() {
		return listaMarcaActivo;
	}

	public void setListaMarcaActivo(List<Activos> listaMarcaActivo) {
		this.listaMarcaActivo = listaMarcaActivo;
	}

	@OneToMany(mappedBy="modelo", fetch=FetchType.LAZY)
	public List<Activos> getListaModeloActivo() {
		return listaModeloActivo;
	}

	public void setListaModeloActivo(List<Activos> listaModeloActivo) {
		this.listaModeloActivo = listaModeloActivo;
	}

	@Column(name="pasivo", nullable=false)
	public boolean isPasivo() {
		return pasivo;
	}

	public void setPasivo(boolean pasivo) {
		this.pasivo = pasivo;
	}	
	
}
