package ni.gob.inss.sisinv.model.entity.catalogo;
// default package
// Generated 09-22-2016 09:39:20 AM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import ni.gob.inss.barista.model.entity.EntityBase;

/**
 * MarcasModelos generated by hbm2java
 */
@Entity
@Table(name = "marcas_modelos", schema = "catalogo")
@SequenceGenerator(name="MarcasModelos_SEQ", sequenceName="catalogo.marcas_modelos_id_seq", allocationSize=1)
public class MarcasModelos extends EntityBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String descripcion;
	private Integer padreId;
	
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MarcasModelos_SEQ")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "padre_id", nullable = false)
	public Integer getPadreId() {
		return this.padreId;
	}

	public void setPadreId(Integer padreId) {
		this.padreId = padreId;
	}

}
