package ni.gob.inss.sisinv.model.entity.catalogo;
// Generated 09-06-2016 02:07:33 PM by Hibernate Tools 4.3.4.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import com.sun.faces.mgbean.ManagedBeanPreProcessingException.Type;

import ni.gob.inss.barista.model.entity.EntityBase;
import ni.gob.inss.barista.model.entity.catalogo.Catalogo;
import ni.gob.inss.sisinv.model.entity.inventario.Activos;

/**
 * Secaf generated by hbm2java
 */
@Entity
@Table(name = "secaf", schema = "catalogo", uniqueConstraints = {@UniqueConstraint(columnNames={"cuenta","subcuenta","digito_auxiliar","objeto"})})
@SequenceGenerator(name="Secaf_SEQ", sequenceName="catalogo.secaf_id_seq")
public class Secaf extends EntityBase implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer cuenta;
	private Integer subcuenta;
	private String digitoAuxiliar;
	private Integer objeto;
	private Integer tipoBien;
	private String cbs;
	private String descripcionCbs;	
	private boolean pasivo;
	private Integer gasto;
	private Catalogo tipoBienCatalogo;
	private List<Activos> listaActivos = new ArrayList<Activos>();

	private Integer tipoMantenimiento;
	private Catalogo oTipoMantenimiento;
	private Integer tipoActivo;
	private Catalogo oTipoActivo;
	
	
	@Id
	@Column(name = "id", unique = true, nullable = false, columnDefinition="serial")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="Secaf_SEQ")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cuenta", nullable = false)
	public Integer getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Integer cuenta) {
		this.cuenta = cuenta;
	}

	@Column(name = "subcuenta", nullable = false)
	public Integer getSubcuenta() {
		return this.subcuenta;
	}

	public void setSubcuenta(Integer subcuenta) {
		this.subcuenta = subcuenta;
	}
	
	@NotNull
	@Column(name = "digito_auxiliar", nullable = false,insertable=true, updatable=true, length = 1)
	public String getDigitoAuxiliar() {
		return digitoAuxiliar;
	}

	public void setDigitoAuxiliar(String digitoAuxiliar) {
		this.digitoAuxiliar = digitoAuxiliar;
	}

	@Column(name = "objeto")
	public Integer getObjeto() {
		return this.objeto;
	}

	public void setObjeto(Integer objeto) {
		this.objeto = objeto;
	}

	@Column(name = "cbs", nullable = false, length = 20, unique=true)
	public String getCbs() {
		return this.cbs;
	}

	public void setCbs(String cbs) {
		this.cbs = cbs;
	}

	@Column(name = "descripcion_cbs", nullable = false, length = 250)
	public String getDescripcionCbs() {
		return this.descripcionCbs;
	}

	public void setDescripcionCbs(String descripcionCbs) {
		this.descripcionCbs = descripcionCbs;
	}


	@Column(name = "pasivo", nullable = false)
	public boolean isPasivo() {
		return this.pasivo;
	}

	public void setPasivo(boolean pasivo) {
		this.pasivo = pasivo;
	}

	@Column(name="tipo_bien", nullable=false)
	public Integer getTipoBien() {
		return tipoBien;
	}

	public void setTipoBien(Integer tipoBien) {
		this.tipoBien = tipoBien;
	}

	@Column(name="gasto", nullable=false, insertable=true, updatable=true)
	public Integer getGasto() {
		return gasto;
	}

	public void setGasto(Integer gasto) {
		this.gasto = gasto;
	}

	@OneToMany(mappedBy = "secaf", fetch = FetchType.LAZY)
	public List<Activos> getListaActivos() {
		return listaActivos;
	}

	public void setListaActivos(List<Activos> listaActivos) {
		this.listaActivos = listaActivos;
	}

	@ManyToOne(fetch= FetchType.EAGER)
	@JoinColumn(name="tipo_bien", updatable=false, insertable=false)
	public Catalogo getTipoBienCatalogo() {
		return tipoBienCatalogo;
	}

	public void setTipoBienCatalogo(Catalogo tipoBienCatalogo) {
		this.tipoBienCatalogo = tipoBienCatalogo;
	}

	@Column(name="tipo_mantenimiento")
	public Integer getTipoMantenimiento() {
		return tipoMantenimiento;
	}

	public void setTipoMantenimiento(Integer tipoMantenimiento) {
		this.tipoMantenimiento = tipoMantenimiento;
	}
	
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="tipo_mantenimiento", updatable=false, insertable=false)
	public Catalogo getoTipoMantenimiento() {
		return oTipoMantenimiento;
	}

	public void setoTipoMantenimiento(Catalogo oTipoMantenimiento) {
		this.oTipoMantenimiento = oTipoMantenimiento;
	}

	@Column(name="tipo_activo")
	public Integer getTipoActivo() {
		return tipoActivo;
	}

	public void setTipoActivo(Integer tipoActivo) {
		this.tipoActivo = tipoActivo;
	}

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="tipo_activo", updatable=false, insertable= false)
	public Catalogo getoTipoActivo() {
		return oTipoActivo;
	}

	public void setoTipoActivo(Catalogo oTipoActivo) {
		this.oTipoActivo = oTipoActivo;
	}
}
