package ni.gob.inss.sisinv.model.entity.catalogo;
// Generated 11-29-2016 09:04:36 AM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import ni.gob.inss.barista.model.entity.EntityBase;

/**
 * TipoActivoCaracteristicasHardware generated by hbm2java
 */
@Entity
@Table(name = "tipo_activo_caracteristicas_hardware", schema = "catalogo", uniqueConstraints = @UniqueConstraint(columnNames = {
		"tipo_activo_id", "caracteristica_padre_id" }))
public class TipoActivoCaracteristicasHardware extends EntityBase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer tipoActivoId;
	private Integer caracteristicaPadreId;
	private Boolean pasivo;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tipo_activo_id", nullable = false)
	public Integer getTipoActivoId() {
		return this.tipoActivoId;
	}

	public void setTipoActivoId(Integer tipoActivoId) {
		this.tipoActivoId = tipoActivoId;
	}

	@Column(name = "caracteristica_padre_id", nullable = false)
	public Integer getCaracteristicaPadreId() {
		return this.caracteristicaPadreId;
	}

	public void setCaracteristicaPadreId(Integer caracteristicaPadreId) {
		this.caracteristicaPadreId = caracteristicaPadreId;
	}

	@Column(name = "pasivo")
	public Boolean getPasivo() {
		return this.pasivo;
	}

	public void setPasivo(Boolean pasivo) {
		this.pasivo = pasivo;
	}

}
