// default package
// Generated 09-20-2016 12:00:41 PM by Hibernate Tools 4.3.4.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivosCaracteristicas generated by hbm2java
 */
@Entity
@Table(name="activos_caracteristicas"
    ,schema="inventario"
)
public class ActivosCaracteristicas  implements java.io.Serializable {


     private ActivosCaracteristicasId id;
     private String valor;
     private boolean esCatalogo;
     private Date creadoEl;
     private Date modificadoEl;
     private Integer creadoPor;
     private Integer modificadoPor;
     private String creadoEnIp;
     private String modificadoEnIp;

    public ActivosCaracteristicas() {
    }

	
    public ActivosCaracteristicas(ActivosCaracteristicasId id, String valor, boolean esCatalogo, Date creadoEl, Integer creadoPor, String creadoEnIp) {
        this.id = id;
        this.valor = valor;
        this.esCatalogo = esCatalogo;
        this.creadoEl = creadoEl;
        this.creadoPor = creadoPor;
        this.creadoEnIp = creadoEnIp;
    }
    public ActivosCaracteristicas(ActivosCaracteristicasId id, String valor, boolean esCatalogo, Date creadoEl, Date modificadoEl, Integer creadoPor, Integer modificadoPor, String creadoEnIp, String modificadoEnIp) {
       this.id = id;
       this.valor = valor;
       this.esCatalogo = esCatalogo;
       this.creadoEl = creadoEl;
       this.modificadoEl = modificadoEl;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.creadoEnIp = creadoEnIp;
       this.modificadoEnIp = modificadoEnIp;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="activos", column=@Column(name="activo_id", nullable=false) ), 
        @AttributeOverride(name="caracteristcaId", column=@Column(name="caracteristca_id", nullable=false) ) } )
    public ActivosCaracteristicasId getId() {
        return this.id;
    }
    
    public void setId(ActivosCaracteristicasId id) {
        this.id = id;
    }

    
    @Column(name="valor", nullable=false, length=50)
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    
    @Column(name="es_catalogo", nullable=false)
    public boolean isEsCatalogo() {
        return this.esCatalogo;
    }
    
    public void setEsCatalogo(boolean esCatalogo) {
        this.esCatalogo = esCatalogo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creado_el", nullable=false, length=29)
    public Date getCreadoEl() {
        return this.creadoEl;
    }
    
    public void setCreadoEl(Date creadoEl) {
        this.creadoEl = creadoEl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modificado_el", length=29)
    public Date getModificadoEl() {
        return this.modificadoEl;
    }
    
    public void setModificadoEl(Date modificadoEl) {
        this.modificadoEl = modificadoEl;
    }

    
    @Column(name="creado_por", nullable=false)
    public Integer getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(Integer creadoPor) {
        this.creadoPor = creadoPor;
    }

    
    @Column(name="modificado_por")
    public Integer getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(Integer modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    
    @Column(name="creado_en_ip", nullable=false, length=20)
    public String getCreadoEnIp() {
        return this.creadoEnIp;
    }
    
    public void setCreadoEnIp(String creadoEnIp) {
        this.creadoEnIp = creadoEnIp;
    }

    
    @Column(name="modificado_en_ip", length=20)
    public String getModificadoEnIp() {
        return this.modificadoEnIp;
    }
    
    public void setModificadoEnIp(String modificadoEnIp) {
        this.modificadoEnIp = modificadoEnIp;
    }




}


