package ni.gob.inss.sisinv.model.entity.inventario;
// Generated 09-20-2016 12:00:41 PM by Hibernate Tools 4.3.4.Final


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import ni.gob.inss.barista.model.entity.EntityBase;

/**
 * ActivosEmpleados generated by hbm2java
 */
@Entity
@Table(name="activos_empleados",schema="inventario")
public class ActivosEmpleados  extends EntityBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ActivosEmpleadosId id;
    private boolean pasivo;
    private Date fechaAsignacion;

   
     @EmbeddedId
     @AttributeOverrides( {
     @AttributeOverride(name="activoId", column=@Column(name="activo_id", nullable=false) ), 
     @AttributeOverride(name="empleadoId", column=@Column(name="empleado_id", nullable=false) ) } )
    public ActivosEmpleadosId getId() {
        return this.id;
    }
    
    public void setId(ActivosEmpleadosId id) {
        this.id = id;
    }

    
    @Column(name="pasivo", nullable=false)
    public boolean isPasivo() {
        return this.pasivo;
    }
    
    public void setPasivo(boolean pasivo) {
        this.pasivo = pasivo;
    }

    
    @Column(name="fecha_asignacion", nullable=false, length=29)
    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }
    
    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }

}