package ni.gob.inss.sisinv.model.entity.inventario;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import ni.gob.inss.barista.model.entity.EntityBase;

/**
 * ActivosCaracteristicas generated by hbm2java
 */
@Entity
@Table(name="activos_caracteristicas" ,schema="inventario")
@IdClass(ActivosCaracteristicasId.class)
public class ActivosCaracteristicas extends EntityBase  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String valor;
    private boolean esCatalogo;
    private Integer activoId;
    private String caracteristicaCodigo;
    private Activos activo;
     
    
    @Id
    @Column(name="activo_id")
    public Integer getActivoId() {
		return activoId;
	}

	public void setActivoId(Integer activoId) {
		this.activoId = activoId;
	}
	@Id
	@Column(name="caracteristica_cod")
	public String getCaracteristicaCodigo() {
		return caracteristicaCodigo;
	}

	public void setCaracteristicaCodigo(String caracteristicaCodigo) {
		this.caracteristicaCodigo = caracteristicaCodigo;
	}

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="activo_id")
	public Activos getActivo() {
		return activo;
	}

	public void setActivo(Activos activo) {
		this.activo = activo;
	}

	@Column(name="valor", nullable=false, length=50)
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    
    @Column(name="es_catalogo", nullable=false)
    public boolean isEsCatalogo() {
        return this.esCatalogo;
    }
    
    public void setEsCatalogo(boolean esCatalogo) {
        this.esCatalogo = esCatalogo;
    }

    
}


