package ni.gob.inss.sisinv.model.entity.inventario;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import ni.gob.inss.barista.model.entity.EntityBase;

/**
 * ActivosCaracteristicas generated by hbm2java
 */
@Entity
@Table(name="activos_caracteristicas" ,schema="inventario")
public class ActivosCaracteristicas extends EntityBase  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ActivosCaracteristicasId id;
    private String valor;
    private boolean esCatalogo;
     
       
     @EmbeddedId
     @AttributeOverrides( {
        @AttributeOverride(name="activoId", column=@Column(name="activo_id", nullable=false) ), 
        @AttributeOverride(name="caracteristcaId", column=@Column(name="caracteristca_id", nullable=false) ) } )
    public ActivosCaracteristicasId getId() {
        return this.id;
    }
    
    public void setId(ActivosCaracteristicasId id) {
        this.id = id;
    }

    
    @Column(name="valor", nullable=false, length=50)
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    
    @Column(name="es_catalogo", nullable=false)
    public boolean isEsCatalogo() {
        return this.esCatalogo;
    }
    
    public void setEsCatalogo(boolean esCatalogo) {
        this.esCatalogo = esCatalogo;
    }

    
}


