package ni.gob.inss.sisinv.model.entity.inventario;
// Generated 10-10-2016 04:13:07 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;

/**
 * ActivosCaracteristicasId generated by hbm2java
 */
@Embeddable
public class ActivosCaracteristicasId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Activos activoId;
	private String caracteristicaCod;

	@ManyToOne
	public Activos getActivoId() {
		return activoId;
	}

	public void setActivoId(Activos activoId) {
		this.activoId = activoId;
	}
	
	@Column(name = "caracteristica_cod", nullable = false, length = 20)
	public String getCaracteristicaCod() {
		return this.caracteristicaCod;
	}
	
	public void setCaracteristicaCod(String caracteristicaCod) {
		this.caracteristicaCod = caracteristicaCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActivosCaracteristicasId))
			return false;
		ActivosCaracteristicasId castOther = (ActivosCaracteristicasId) other;

		return ((this.getActivoId() == castOther.getActivoId()) || (this.getActivoId() != null
				&& castOther.getActivoId() != null && this.getActivoId().equals(castOther.getActivoId())))
				&& ((this.getCaracteristicaCod() == castOther.getCaracteristicaCod())
						|| (this.getCaracteristicaCod() != null && castOther.getCaracteristicaCod() != null
								&& this.getCaracteristicaCod().equals(castOther.getCaracteristicaCod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getActivoId() == null ? 0 : this.getActivoId().hashCode());
		result = 37 * result + (getCaracteristicaCod() == null ? 0 : this.getCaracteristicaCod().hashCode());
		return result;
	}

}
