// default package
// Generated 09-20-2016 12:00:41 PM by Hibernate Tools 4.3.4.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivosEmpleados generated by hbm2java
 */
@Entity
@Table(name="activos_empleados"
    ,schema="inventario"
)
public class ActivosEmpleados  implements java.io.Serializable {


     private ActivosEmpleadosId id;
     private boolean pasivo;
     private Integer creadoPor;
     private Integer modificadoPor;
     private Date creadoEl;
     private Date modificadoEl;
     private String creadoEnIp;
     private String modificadoEnIp;
     private Date fechaAsignacion;

    public ActivosEmpleados() {
    }

	
    public ActivosEmpleados(ActivosEmpleadosId id, boolean pasivo, Integer creadoPor, Date creadoEl, Date fechaAsignacion) {
        this.id = id;
        this.pasivo = pasivo;
        this.creadoPor = creadoPor;
        this.creadoEl = creadoEl;
        this.fechaAsignacion = fechaAsignacion;
    }
    public ActivosEmpleados(ActivosEmpleadosId id, boolean pasivo, Integer creadoPor, Integer modificadoPor, Date creadoEl, Date modificadoEl, String creadoEnIp, String modificadoEnIp, Date fechaAsignacion) {
       this.id = id;
       this.pasivo = pasivo;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.creadoEl = creadoEl;
       this.modificadoEl = modificadoEl;
       this.creadoEnIp = creadoEnIp;
       this.modificadoEnIp = modificadoEnIp;
       this.fechaAsignacion = fechaAsignacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="activos", column=@Column(name="activo_id", nullable=false) ), 
        @AttributeOverride(name="empleadoId", column=@Column(name="empleado_id", nullable=false) ) } )
    public ActivosEmpleadosId getId() {
        return this.id;
    }
    
    public void setId(ActivosEmpleadosId id) {
        this.id = id;
    }

    
    @Column(name="pasivo", nullable=false)
    public boolean isPasivo() {
        return this.pasivo;
    }
    
    public void setPasivo(boolean pasivo) {
        this.pasivo = pasivo;
    }

    
    @Column(name="creado_por", nullable=false)
    public Integer getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(Integer creadoPor) {
        this.creadoPor = creadoPor;
    }

    
    @Column(name="modificado_por")
    public Integer getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(Integer modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creado_el", nullable=false, length=29)
    public Date getCreadoEl() {
        return this.creadoEl;
    }
    
    public void setCreadoEl(Date creadoEl) {
        this.creadoEl = creadoEl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modificado_el", length=29)
    public Date getModificadoEl() {
        return this.modificadoEl;
    }
    
    public void setModificadoEl(Date modificadoEl) {
        this.modificadoEl = modificadoEl;
    }

    
    @Column(name="creado_en_ip", length=20)
    public String getCreadoEnIp() {
        return this.creadoEnIp;
    }
    
    public void setCreadoEnIp(String creadoEnIp) {
        this.creadoEnIp = creadoEnIp;
    }

    
    @Column(name="modificado_en_ip", length=20)
    public String getModificadoEnIp() {
        return this.modificadoEnIp;
    }
    
    public void setModificadoEnIp(String modificadoEnIp) {
        this.modificadoEnIp = modificadoEnIp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_asignacion", nullable=false, length=29)
    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }
    
    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }




}


