package ni.gob.inss.sisinv.model.entity.inventario;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import ni.gob.inss.barista.model.entity.EntityBase;
import ni.gob.inss.sisinv.model.entity.catalogo.Empleado;

/**
 * Activos generated by hbm2java
 */
@Entity
@Table(name = "activos", schema = "inventario", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_inventario"))
@SequenceGenerator(name="Activos_SEQ", sequenceName="inventario.activos_id_seq", allocationSize=1)
public class Activos extends EntityBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer secafId;
	private String codigoInventario;
	private String codigoSecundario;
	private String descripcion;
	private Integer marcaId;
	private Integer modeloId;
	private String serie;
	private Date fechaAdquisicion;
	private Integer estadoFisicoId;
	private Integer tipoResguardoId;
	private String numeroProyecto;
	private String numeroBodega;
	private boolean pasivo;
	private BigDecimal valor;
	private Integer tipoMoneda;
	private String lote;
	private Empleado empleado;
	private Integer ubicacionId;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="Activos_SEQ")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "secaf_id", nullable = false)
	public Integer getSecafId() {
		return this.secafId;
	}

	public void setSecafId(Integer secafId) {
		this.secafId = secafId;
	}

	@Column(name = "codigo_inventario", unique = true, nullable = false, length = 30)
	public String getCodigoInventario() {
		return this.codigoInventario;
	}

	public void setCodigoInventario(String codigoInventario) {
		this.codigoInventario = codigoInventario;
	}

	@Column(name = "codigo_secundario", length = 30)
	public String getCodigoSecundario() {
		return this.codigoSecundario;
	}

	public void setCodigoSecundario(String codigoSecundario) {
		this.codigoSecundario = codigoSecundario;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "marca_id", nullable = false)
	public Integer getMarcaId() {
		return this.marcaId;
	}

	public void setMarcaId(Integer marcaId) {
		this.marcaId = marcaId;
	}

	@Column(name = "modelo_id", nullable = false)
	public Integer getModeloId() {
		return this.modeloId;
	}

	public void setModeloId(Integer modeloId) {
		this.modeloId = modeloId;
	}

	@Column(name = "serie", length = 50)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adquisicion", length = 29)
	public Date getFechaAdquisicion() {
		return this.fechaAdquisicion;
	}

	public void setFechaAdquisicion(Date fechaAdquisicion) {
		this.fechaAdquisicion = fechaAdquisicion;
	}

	@Column(name = "estado_fisico_id", nullable = false)
	public Integer getEstadoFisicoId() {
		return this.estadoFisicoId;
	}

	public void setEstadoFisicoId(Integer estadoFisicoId) {
		this.estadoFisicoId = estadoFisicoId;
	}

	@Column(name = "tipo_resguardo_id", nullable = false)
	public Integer getTipoResguardoId() {
		return this.tipoResguardoId;
	}

	public void setTipoResguardoId(Integer tipoResguardoId) {
		this.tipoResguardoId = tipoResguardoId;
	}

	@Column(name = "numero_proyecto", length = 20)
	public String getNumeroProyecto() {
		return this.numeroProyecto;
	}

	public void setNumeroProyecto(String numeroProyecto) {
		this.numeroProyecto = numeroProyecto;
	}

	@Column(name = "numero_bodega", length = 20)
	public String getNumeroBodega() {
		return this.numeroBodega;
	}

	public void setNumeroBodega(String numeroBodega) {
		this.numeroBodega = numeroBodega;
	}

	@Column(name = "pasivo", nullable = false)
	public boolean isPasivo() {
		return this.pasivo;
	}

	public void setPasivo(boolean pasivo) {
		this.pasivo = pasivo;
	}

	
	@Column(name = "valor", precision = 10)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "tipo_moneda", nullable = false)
	public Integer getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(Integer tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	@Column(name = "lote", length = 20)
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "empleadoId")
	public Empleado getEmpleado() {
		return empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Integer getUbicacionId() {
		return ubicacionId;
	}

	public void setUbicacionId(Integer ubicacionId) {
		this.ubicacionId = ubicacionId;
	}
	
	
}
