// default package
// Generated 09-20-2016 12:02:34 PM by Hibernate Tools 4.3.4.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Activos generated by hbm2java
 */
@Entity
@Table(name = "activos", schema = "inventario", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_inventario"))
public class Activos implements java.io.Serializable {

	private Integer id;
	private Integer secafId;
	private String codigoInventario;
	private String codigoSecundario;
	private String descripcion;
	private Integer marcaId;
	private Integer modeloId;
	private String serie;
	private Date fechaAdquisicion;
	private Integer estadoFisicoId;
	private Integer tipoResguardoId;
	private String numeroProyecto;
	private String numeroBodega;
	private boolean pasivo;
	private Date creadoEl;
	private String modificadoEl;
	private Integer creadoPor;
	private Integer modificadoPor;
	private String creadoEnIp;
	private String modificadoEnIp;
	private BigDecimal valor;
	private Integer tipoMoneda;
	private String lote;

	public Activos() {
	}

	public Activos(Integer id, Integer secafId, String codigoInventario, String descripcion, Integer marcaId,
			Integer modeloId, Integer estadoFisicoId, Integer tipoResguardoId, boolean pasivo, Date creadoEl,
			Integer creadoPor, String creadoEnIp, Integer tipoMoneda) {
		this.id = id;
		this.secafId = secafId;
		this.codigoInventario = codigoInventario;
		this.descripcion = descripcion;
		this.marcaId = marcaId;
		this.modeloId = modeloId;
		this.estadoFisicoId = estadoFisicoId;
		this.tipoResguardoId = tipoResguardoId;
		this.pasivo = pasivo;
		this.creadoEl = creadoEl;
		this.creadoPor = creadoPor;
		this.creadoEnIp = creadoEnIp;
		this.tipoMoneda = tipoMoneda;
	}

	public Activos(Integer id, Integer secafId, String codigoInventario, String codigoSecundario, String descripcion,
			Integer marcaId, Integer modeloId, String serie, Date fechaAdquisicion, Integer estadoFisicoId,
			Integer tipoResguardoId, String numeroProyecto, String numeroBodega, boolean pasivo, Date creadoEl,
			String modificadoEl, Integer creadoPor, Integer modificadoPor, String creadoEnIp, String modificadoEnIp,
			BigDecimal valor, Integer tipoMoneda, String lote) {
		this.id = id;
		this.secafId = secafId;
		this.codigoInventario = codigoInventario;
		this.codigoSecundario = codigoSecundario;
		this.descripcion = descripcion;
		this.marcaId = marcaId;
		this.modeloId = modeloId;
		this.serie = serie;
		this.fechaAdquisicion = fechaAdquisicion;
		this.estadoFisicoId = estadoFisicoId;
		this.tipoResguardoId = tipoResguardoId;
		this.numeroProyecto = numeroProyecto;
		this.numeroBodega = numeroBodega;
		this.pasivo = pasivo;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.creadoPor = creadoPor;
		this.modificadoPor = modificadoPor;
		this.creadoEnIp = creadoEnIp;
		this.modificadoEnIp = modificadoEnIp;
		this.valor = valor;
		this.tipoMoneda = tipoMoneda;
		this.lote = lote;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "secaf_id", nullable = false)
	public Integer getSecafId() {
		return this.secafId;
	}

	public void setSecafId(Integer secafId) {
		this.secafId = secafId;
	}

	@Column(name = "codigo_inventario", unique = true, nullable = false, length = 30)
	public String getCodigoInventario() {
		return this.codigoInventario;
	}

	public void setCodigoInventario(String codigoInventario) {
		this.codigoInventario = codigoInventario;
	}

	@Column(name = "codigo_secundario", length = 30)
	public String getCodigoSecundario() {
		return this.codigoSecundario;
	}

	public void setCodigoSecundario(String codigoSecundario) {
		this.codigoSecundario = codigoSecundario;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "marca_id", nullable = false)
	public Integer getMarcaId() {
		return this.marcaId;
	}

	public void setMarcaId(Integer marcaId) {
		this.marcaId = marcaId;
	}

	@Column(name = "modelo_id", nullable = false)
	public Integer getModeloId() {
		return this.modeloId;
	}

	public void setModeloId(Integer modeloId) {
		this.modeloId = modeloId;
	}

	@Column(name = "serie", length = 50)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adquisicion", length = 29)
	public Date getFechaAdquisicion() {
		return this.fechaAdquisicion;
	}

	public void setFechaAdquisicion(Date fechaAdquisicion) {
		this.fechaAdquisicion = fechaAdquisicion;
	}

	@Column(name = "estado_fisico_id", nullable = false)
	public Integer getEstadoFisicoId() {
		return this.estadoFisicoId;
	}

	public void setEstadoFisicoId(Integer estadoFisicoId) {
		this.estadoFisicoId = estadoFisicoId;
	}

	@Column(name = "tipo_resguardo_id", nullable = false)
	public Integer getTipoResguardoId() {
		return this.tipoResguardoId;
	}

	public void setTipoResguardoId(Integer tipoResguardoId) {
		this.tipoResguardoId = tipoResguardoId;
	}

	@Column(name = "numero_proyecto", length = 20)
	public String getNumeroProyecto() {
		return this.numeroProyecto;
	}

	public void setNumeroProyecto(String numeroProyecto) {
		this.numeroProyecto = numeroProyecto;
	}

	@Column(name = "numero_bodega", length = 20)
	public String getNumeroBodega() {
		return this.numeroBodega;
	}

	public void setNumeroBodega(String numeroBodega) {
		this.numeroBodega = numeroBodega;
	}

	@Column(name = "pasivo", nullable = false)
	public boolean isPasivo() {
		return this.pasivo;
	}

	public void setPasivo(boolean pasivo) {
		this.pasivo = pasivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_el", nullable = false, length = 29)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Column(name = "modificado_el", length = 50)
	public String getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(String modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "creado_por", nullable = false)
	public Integer getCreadoPor() {
		return this.creadoPor;
	}

	public void setCreadoPor(Integer creadoPor) {
		this.creadoPor = creadoPor;
	}

	@Column(name = "modificado_por")
	public Integer getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(Integer modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

	@Column(name = "creado_en_ip", nullable = false, length = 20)
	public String getCreadoEnIp() {
		return this.creadoEnIp;
	}

	public void setCreadoEnIp(String creadoEnIp) {
		this.creadoEnIp = creadoEnIp;
	}

	@Column(name = "modificado_en_ip", length = 20)
	public String getModificadoEnIp() {
		return this.modificadoEnIp;
	}

	public void setModificadoEnIp(String modificadoEnIp) {
		this.modificadoEnIp = modificadoEnIp;
	}

	@Column(name = "valor", precision = 10)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "tipo_moneda", nullable = false)
	public Integer getTipoMoneda() {
		return this.tipoMoneda;
	}

	public void setTipoMoneda(Integer tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	@Column(name = "lote", length = 20)
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

}
